name: Test
on: [push]
jobs:

  build:
    name: Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Download module dependencies
      run: go mod download

    - name: License Check
      run: make license-check

    - name: Lint
      run: make lint

    - name: Test and Coverage
      run: COVERALLS_TOKEN=${{ secrets.COVERALLS_TOKEN }} make coverage
